apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: frontend # tên ReplicaSet
  labels:
    app: guestbook
    tier: frontend
spec:
  replicas: 3 # số pod được duy trì
  selector:
    matchLabels:
      tier: frontend # chọn pod có label này
  template:
    metadata:
      labels:
        tier: frontend # label pod mới
    spec:
      containers:
        - name: php-redis
          image: us-docker.pkg.dev/google-samples/containers/gke/gb-frontend:v5
